---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: tools
data:
  config.json: |
    {
      
      "platform": "github",
      "autodiscover": true,
      "autodiscoverFilter": ["!old-*"],
      "detectHostRulesFromEnv": true,
      "gitAuthor": "Renovate Bot <renovate@renovate-app.com>"
    }
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: tools
spec:
  schedule: "0 12 * * 5"
  timeZone: "Europe/Budapest"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: renovate
              image: renovate/renovate:latest
              env:
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: infra-secrets
                      key: RENOVATE_TOKEN
                - name: RENOVATE_BASE_DIR
                  value: '/tmp/renovate/'
                - name: RENOVATE_CONFIG_FILE
                  value: '/opt/renovate/config.json'
                - name: LOG_LEVEL
                  value: info
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
              resources:
                requests:
                  cpu: "500"
                  memory: "1Gi"
                limits:
                  cpu: "750m"
                  memory: "2Gi"
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: { }
